<?php
session_start();
if(isset($_SESSION['ST_USER']))
{
session_destroy();
header("Location:index.php");
}
if(isset($_SESSION['T_USER']))
{
session_destroy();
header("Location:index.php");
}
if(isset($_SESSION['A_USER']))
{
session_destroy();
header("Location:index.php");
}
?>